services:
  farm-landing:
    build: .
    container_name: farm-landing
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.farm-landing.rule=Host(`sterveai.sterveshop.cloud`)"
      - "traefik.http.routers.farm-landing.entrypoints=websecure"
      - "traefik.http.routers.farm-landing.tls=true"
      - "traefik.http.routers.farm-landing.tls.certresolver=letsencrypt"

      - "traefik.http.routers.farm-landing-http.rule=Host(`sterveai.sterveshop.cloud`)"
      - "traefik.http.routers.farm-landing-http.entrypoints=web"
      - "traefik.http.routers.farm-landing-http.middlewares=redirect-https"

      - "traefik.http.services.farm-landing.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
