"""initial schema

Revision ID: e34c625cda4f
Revises: 
Create Date: 2026-02-22 08:30:09.645457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34c625cda4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_posts', sa.Column('bullets', sa.JSON(), nullable=True))
    op.alter_column('linkedin_posts', 'post_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MILESTONE', 'UPDATE', 'LEARNING', name='posttype'),
               existing_nullable=False)
    op.alter_column('linkedin_posts', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'PROCESSING', 'READY', 'PUBLISHED', 'FAILED', name='poststatus'),
               nullable=False)
    op.drop_column('linkedin_posts', 'bullet3')
    op.drop_column('linkedin_posts', 'bullet1')
    op.drop_column('linkedin_posts', 'buffer_post_id')
    op.drop_column('linkedin_posts', 'bullet2')
    op.drop_column('users', 'buffer_profile_id')
    op.drop_column('users', 'buffer_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('buffer_access_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('buffer_profile_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('linkedin_posts', sa.Column('bullet2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('linkedin_posts', sa.Column('buffer_post_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('linkedin_posts', sa.Column('bullet1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('linkedin_posts', sa.Column('bullet3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('linkedin_posts', 'status',
               existing_type=sa.Enum('DRAFT', 'PROCESSING', 'READY', 'PUBLISHED', 'FAILED', name='poststatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('linkedin_posts', 'post_type',
               existing_type=sa.Enum('MILESTONE', 'UPDATE', 'LEARNING', name='posttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('linkedin_posts', 'bullets')
    # ### end Alembic commands ###
